# Generated by Django 4.2.11 on 2024-04-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commune_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=100)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CommuneTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alternativkostnaderApp.commune",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alternativkostnaderApp.technology",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commune",
            name="technologies",
            field=models.ManyToManyField(
                through="alternativkostnaderApp.CommuneTech",
                to="alternativkostnaderApp.technology",
            ),
        ),
    ]
