# Generated by Django 4.2.11 on 2024-04-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commune_name", models.CharField(max_length=200)),
                ("type_of_commune", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CommuneTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology_name", models.CharField(max_length=200)),
                ("total_installation", models.IntegerField()),
                ("potential_installation", models.IntegerField()),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alternativkostnaderApp.commune",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commune",
            name="technologies",
            field=models.ManyToManyField(to="alternativkostnaderApp.tech"),
        ),
    ]
