# Generated by Django 4.2.11 on 2024-04-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alternativkostnaderApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="technologies",
        ),
        migrations.AddField(
            model_name="technology",
            name="commune_name",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technologies",
                to="alternativkostnaderApp.commune",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="technology",
            unique_together={("tech_name", "value")},
        ),
        migrations.DeleteModel(
            name="CommuneTech",
        ),
    ]
