# Generated by Django 4.2.11 on 2024-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternativkostnaderApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="type_of_commune",
        ),
        migrations.RemoveField(
            model_name="communetechnology",
            name="commune",
        ),
        migrations.RemoveField(
            model_name="tech",
            name="tech_name",
        ),
        migrations.AddField(
            model_name="tech",
            name="technologies",
            field=models.ManyToManyField(to="alternativkostnaderApp.communetechnology"),
        ),
    ]
