# Generated by Django 4.2.11 on 2024-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternativkostnaderApp", "0002_remove_commune_type_of_commune_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="technologies",
            field=models.ManyToManyField(to="alternativkostnaderApp.communetechnology"),
        ),
        migrations.DeleteModel(
            name="Tech",
        ),
    ]
