# Generated by Django 4.2.11 on 2024-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alternativkostnaderApp", "0003_alter_technology_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="commune_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
