# Generated by Django 4.2.11 on 2024-04-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "alternativkostnaderApp",
            "0005_rename_value_technology_antal_installationer_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="technology",
            old_name="Årlig_besparing_per_installation_HTE",
            new_name="Arlig_besparing_per_installation_HTE",
        ),
        migrations.RenameField(
            model_name="technology",
            old_name="Årlig_besparing_per_installation_SEK",
            new_name="Arlig_besparing_per_installation_SEK",
        ),
    ]
