# Generated by Django 4.2.11 on 2024-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternativkostnaderApp', '0006_rename_årlig_besparing_per_installation_hte_technology_arlig_besparing_per_installation_hte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='id',
        ),
        migrations.AlterField(
            model_name='commune',
            name='commune_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
