# Generated by Django 4.2.11 on 2024-04-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternativkostnaderApp', '0006_rename_årlig_besparing_per_installation_hte_technology_arlig_besparing_per_installation_hte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='Arlig_besparing_per_installation_HTE',
        ),
    ]
